# -*- coding: utf-8 -*-
"""HTML_QUICK_STYLER

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cKJuffkgmvdPMFf4_EvGE9K24kLMXKLc
"""

!pip install gradio transformers torch

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

model_name = "ibm-granite/granite-3.3-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

def generate_ai_response(prompt):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    output = model.generate(**inputs, max_new_tokens=800)
    return tokenizer.decode(output[0], skip_special_tokens=True)

class ColorPaletteGenerator:
    def __init__(self):
        self.palettes = {
            "modern": {
                "primary": "#6366f1",
                "secondary": "#8b5cf6",
                "accent": "#ec4899",
                "background": "#0f172a",
                "surface": "#1e293b",
                "text_primary": "#ffffff",
                "text_secondary": "#94a3b8",
                "border": "#334155"
            },
            "ocean": {
                "primary": "#0ea5e9",
                "secondary": "#06b6d4",
                "accent": "#14b8a6",
                "background": "#0c4a6e",
                "surface": "#075985",
                "text_primary": "#ffffff",
                "text_secondary": "#bae6fd",
                "border": "#0369a1"
            },
            "minimal": {
                "primary": "#111827",
                "secondary": "#374151",
                "accent": "#6b7280",
                "background": "#ffffff",
                "surface": "#f3f4f6",
                "text_primary": "#111827",
                "text_secondary": "#6b7280",
                "border": "#e5e7eb"
            }
        }

    def get_palette(self, style):
        return self.palettes.get(style, self.palettes["modern"])

def generate_css(colors):
    return f"""
    :root {{
        --primary: {colors['primary']};
        --secondary: {colors['secondary']};
        --accent: {colors['accent']};
        --background: {colors['background']};
        --surface: {colors['surface']};
        --text-primary: {colors['text_primary']};
        --text-secondary: {colors['text_secondary']};
        --border: {colors['border']};
    }}

    body {{
        margin: 0;
        font-family: Arial, sans-serif;
        background: var(--background);
        color: var(--text-primary);
    }}

    header {{
        background: var(--surface);
        padding: 20px;
        text-align: center;
        position: sticky;
        top: 0;
    }}

    .hero {{
        padding: 100px 20px;
        text-align: center;
        background: linear-gradient(135deg, var(--primary), var(--secondary));
        color: white;
    }}

    .section {{
        padding: 60px 20px;
    }}

    .card {{
        background: var(--surface);
        padding: 20px;
        border-radius: 10px;
        margin: 10px;
        box-shadow: 0 4px 20px rgba(0,0,0,0.2);
    }}

    .btn {{
        background: var(--accent);
        padding: 10px 20px;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }}

    @media (max-width: 768px) {{
        .hero {{
            padding: 60px 10px;
        }}
    }}
    """

class HTMLPageBuilder:

    def build_page(self, title, description, colors):
        css = generate_css(colors)

        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>{title}</title>
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <style>{css}</style>
        </head>
        <body>

        <header>
            <h1>{title}</h1>
        </header>

        <section class="hero">
            <h2>Welcome to {title}</h2>
            <p>{description}</p>
            <button class="btn">Get Started</button>
        </section>

        <section class="section">
            <div class="card">
                <h3>Feature One</h3>
                <p>Powerful and modern design.</p>
            </div>
            <div class="card">
                <h3>Feature Two</h3>
                <p>Fully responsive layout.</p>
            </div>
        </section>

        <footer class="section">
            <p>© 2026 {title}. All rights reserved.</p>
        </footer>

        </body>
        </html>
        """

        return html

import gradio as gr

palette_gen = ColorPaletteGenerator()
builder = HTMLPageBuilder()

def generate_page(title, description, style):
    colors = palette_gen.get_palette(style)
    return builder.build_page(title, description, colors)

with gr.Blocks() as app:
    gr.Markdown("# HTML Quick-Styler")

    with gr.Tab("Generate Page"):
        title = gr.Textbox(label="Page Title")
        description = gr.Textbox(label="Description")
        style = gr.Dropdown(["modern", "ocean", "minimal"], value="modern")

        output = gr.HTML()

        btn = gr.Button("Generate")
        btn.click(generate_page, inputs=[title, description, style], outputs=output)

app.launch()